---
- hosts: all
  become: true
  vars:
   key_file: /etc/nginx/ssl/nginx.key
   cert_file: /etc/nginx/ssl/nginx.crt
  tasks:
   - name: Clone a private repository
     git:
       repo: https://github.com/hrmanth/beginner-html-site-styled.git
       dest: srv/checkout
       update: no

   - name: Download the repo
     get_url: url=http://nginx.org/packages/rhel/6/noarch/RPMS/nginx-release-rhel-6-0.el6.ngx.noarch.rpm dest=/tmp

   - name: install repo
     command: rpm -ivh nginx-release-rhel-6-0.el6.ngx.noarch.rpm
     args:
      chdir: /tmp/
     ignore_errors: yes

   - name: install nginx webserver
     yum: name=nginx state=installed

   - name: update index.html
     template: src=template/index.html.j2 dest=/usr/share/nginx/html backup=yes mode=644 owner=root group=root

   - name: create ssl directory
     file: path=/etc/nginx/ssl state=directory

   - name: copy key_file to remote server
     copy: src=/root/files/nginx.key dest={{key_file}} mode=400 owner=root group=root

   - name: copy cert file to remote server
     copy: src=files/nginx.crt dest={{cert_file}} mode=644 owner=root group=root

   - name: update defalut.conf file on remote server
     template: src=template/default.conf.j2 dest=/etc/nginx/conf.d/default owner=root mode=644 backup=yes
     notify: restart nginx

  handlers:
   - name: restart nginx
     service: name=nginx state=restarted

